In [48]:
# 1. Convert list of numeric values into a 1 dimensional numpy array. 
import numpy as np
lst = [12.23, 13.32, 100, 36.32, 98, 34]
arr = np.array(lst)
print(arr)

[ 12.23  13.32 100.    36.32  98.    34.  ]


In [49]:
# 2. 3x3 matrix with values ranging from 2 to 10.
arr = np.arange(2,11)
new_arr = arr.reshape(3,3)
print(new_arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [50]:
# 3. program to create null vector of size 10 and update sixth element to value 11.
arr = np.zeros(10)
arr[6] = 11
print(arr)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [51]:
# 4. Program to reverse a given array.
arr = np.array([12, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 
                28, 29, 30, 31, 32, 33, 34, 35, 36, 37])
print(arr[::-1])

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 12 12]


In [52]:
# 5. Create a 2d array with 1 on the border and 0 on the inside.
arr = np.zeros([5,5])
arr[-1,:] = 1
arr[0,:] = 1
arr[:,0] = 1
arr[:,-1] = 1
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [53]:
# 6. Add a border filled with 0's around an existing array.
rows = 4
cols = 4
arr = np.ones([rows,cols])
border_sides = np.zeros(rows)
arr = np.vstack((border_sides, arr, border_sides))
border_sides = np.zeros((rows+2, 1))
arr = np.hstack((border_sides, arr, border_sides))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [54]:
# 7. 8x8 checker board pattern.
checker_board = np.zeros([8,8], dtype = 'i')
checker_board[0::2, 1::2] = 1
checker_board[1::2, 0::2] = 1
print(checker_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [55]:
# 8. Python program to convert a list and tuple to array
lst = [12, 43, 54, 65, 76]
list_arr = np.array(lst)
tup = ((21,34,54,65),(34,54,65,23))
tup_arr = np.array(tup)
print(f"List to array:\n{list_arr}\n")
print(f"Tuple to array:\n{tup_arr}")

List to array:
[12 43 54 65 76]

Tuple to array:
[[21 34 54 65]
 [34 54 65 23]]


In [56]:
# 9. Append values to the end of an array.
arr = np.array([10,20,30])
arr = np.concatenate((arr,[40,50,60,70,80,90]))
print(arr)

[10 20 30 40 50 60 70 80 90]


In [57]:
# 10. Program to print real and imaginary parts of an array of complex numbers.
arr = np.array([1.00000000+0.j, 0.70710678+0.70710678j])
print(f"Real part of the array:\n{arr.real}")
print(f"Imaginary part of the array:\n{arr.imag}")


Real part of the array:
[1.         0.70710678]
Imaginary part of the array:
[0.         0.70710678]


In [58]:
# 11. find the number of elements of an array, length of one array element in bytes 
#     and total bytes consumed by the elements.
arr = np.full((3,3),5)
length = arr.size
item_size = arr.itemsize
print(f"Size of the array: {length}")
print(f"Length of an array element in bytes: {item_size}")
print(f"Total bytes consumed by the elements of the array: {length*item_size}")


Size of the array: 9
Length of an array element in bytes: 8
Total bytes consumed by the elements of the array: 72


In [59]:
# 12. program to find common values between two arrays.
arr1 = np.array([10,30,20,50,40])
arr2 = np.array([30,80,20,40,90])
intersect = np.intersect1d(arr1,arr2, assume_unique = True)
print(intersect)

[20 30 40]


In [60]:
# 13. find the set difference of two arrays. The set difference will return the sorted, 
#     unique values in array1 that are not in array2.
arr1 = np.array([0, 10, 20, 40, 60, 80],dtype='i')
arr2 = np.array([10, 30, 40, 50, 70, 90],dtype='i')
set_diff = np.setdiff1d(arr1,arr2, assume_unique=True)
print(set_diff)

[ 0 20 60 80]


In [61]:
# 14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or 
#     will return the sorted, unique values that are in only one (not both) of the input arrays.
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array( [10, 30, 40, 50, 70])
res_arr = np.setxor1d(arr1,arr2, assume_unique=True)
res_arr

array([ 0, 20, 30, 50, 60, 70, 80])

In [62]:
# 15. Program tto compare 2 arrays using numpy.
arr1 = np.array([1, 2])
arr2 = np.array([4, 5])
print(f"a = {arr1}")
print(f"b = {arr2}")
print(f"a > b:\n{arr1 > arr2}")
print(f"a >= b:\n{arr1 >= arr2}")
print(f"a < b:\n{arr1 < arr2}")
print(f"a <= b:\n{arr1 <= arr2}")

a = [1 2]
b = [4 5]
a > b:
[False False]
a >= b:
[False False]
a < b:
[ True  True]
a <= b:
[ True  True]


In [63]:
# 16. Python program to save numpy array to textfile.
arr = np.array([[29, 40, 50, 60],[90, 120, 59, 12]])
np.savetxt('arr_file.txt', arr, fmt='%d')

arr2 = np.loadtxt('arr_file.txt', dtype='i')
print(arr2)


[[ 29  40  50  60]
 [ 90 120  59  12]]


In [64]:
# 17. Program to create contiguous flattened array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = arr.flatten()
print(flat_arr)

[1 2 3 4 5 6]


In [65]:
# 18. Program to change data type of an array.
arr = np.array([[2, 4, 6], [6, 8, 10]], dtype='i')
print(f"Data type of the array is: {arr.dtype}")
print(arr)
arr = np.astype(arr, np.float64)
print(f"New data type of the array is: {arr.dtype}")
print(arr)


Data type of the array is: int32
[[ 2  4  6]
 [ 6  8 10]]
New data type of the array is: float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


In [66]:
# 19. Program to create a 2D array with ones on a diagonal and zeros elsewhere.
arr = np.zeros((5,5), dtype='i')
# for i in range(3):
#     arr[i,i] = 1
np.fill_diagonal(arr, 1)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [67]:
# 20. Progam to print pattern in array.
rows = 5
cols = 5
arr = np.ones((rows,cols), dtype='i')
print(np.tril(arr, k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [68]:
# 21. Program to concatenate 2D arrays.
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])
print(np.concatenate((arr1, arr2), axis=1))

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [69]:
# 22. Program to make array immutable(read-only).
arr = np.array([90,34,53,54,2])
arr.setflags(write=False)
print(arr)
arr[0] = 23


[90 34 53 54  2]


ValueError: assignment destination is read-only

In [ ]:
# 23. program to create an array of (3, 4) shape, multiply every element 
#     value by 3 and display the new array.
arr = np.array([[0, 1, 2, 3], [4, 5, 6, 7],[8, 9, 10, 11]])
print(arr * 3)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [ ]:
# 24. Write a Python program to convert a NumPy array into Python list structure.
arr = np.array([[0, 1],[2, 3],[4, 5]])
lst = arr.tolist()
print(lst)

[[0, 1], [2, 3], [4, 5]]


In [ ]:
# 25. Write a Python program to convert a NumPy array into Python list structure.(float 3 literals)
arr = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478])
print(f"Original array:\n{arr}")
print(f"Array converted to list with 3 precision values:\n {np.round(arr,3).tolist()}")


Original array:
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Array converted to list with 3 precision values:
 [0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069, 0.547]


In [ ]:
# 26. Python program to suppresses the use of scientific notation for small numbers in numpy array.
arr = np.array([ 1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
np.set_printoptions(suppress=True)
print(arr)

[   0.       1.6   1200.       0.235]


In [ ]:
# 27. Python program to how to add an extra column to an numpy array.
arr = np.array([10, 20, 30, 100])
print(np.vstack((arr, [40, 50, 60, 200])))

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [70]:
# 28. Python program to remove specific elements in a numpy array.
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
arr = np.delete(arr, (0,3,4))
print(arr)

[ 20  30  60  70  80  90 100]
